### PR TITLE
Add Widget e2e tests

### PR DESCRIPTION
**Pull request by donnapep**
* Clean up HTML files
* Fix bug with getting day of week from weather forecast
* Fix settings e2e failing test when saving settings
* Commit `dist` folder

### CODE REVIEW

**Comment by donnapep** [comment]
@alex-deaconu The tests have been fixed as well. Please review. Thx.

**Comment by alex-deaconu** [comment]
@donnapep i18n looks good, and so do the tests. I see you guys decided to commit the dist/ folder as well. Just curious, why did you find that's necessary, and should I be doing that with the financial table? Thanks.

**Comment by donnapep** [comment]
@alex-deaconu We decided to commit the `dist` folder (and also include non-minified versions of the CSS and JS as well) to make it easier for people who aren't developers to make simple changes directly to files in that folder. This is so that they don't have to go through a typical developer set-up of installing bower and all of those other dependencies just to make a simple change. It would be great if you could do that with Financial Table. Cheers.

**Comment by donnapep** [comment]
@alex-deaconu Fonts weren't working in the Widget. Updated the class names to fix this. Please review. Thx.

**Comment by alex-deaconu** [comment]
:+1:

**Comment by donnapep** [comment]
@alex-deaconu I had to revert the changes to the gulpfile so that the locale info that is stored with the Widget code is copied to the `dist` folder as well, since the Widget needs it. The translations for the settings are still coming from common-i18n though. Please review. Thx.

**Comment by alex-deaconu** [comment]
@donnapep I know the reason for doing this is so the translations are also available for i18next.js. However, there's a simpler fix, by configuring i18next translation location. Take a look at this PR to see how I did it in widget-settings-ui-core: https://github.com/Rise-Vision/widget-settings-ui-core/compare/fix/translation-files. Thanks!

**Comment by donnapep** [comment]
@alex-deaconu OK, I've made the change. I had to change the gulpfile to copy the `locales` folder to `src` as well so that the tests would pass.

Also, there's a fix in here for making the Widget work in multi-page Presentations by explicitly setting its size and then setting its back to its original dimensions once all calculations are done. Please review. Thx.

**Comment by alex-deaconu** [comment]
@donnapep LG :+1: . Thanks!

**Pull request merged**
